import { createSlice } from "@reduxjs/toolkit"; // Import the createSlice function from Redux Toolkit

// Define a slice of the Redux store for handling gener state
export const generSlice = createSlice({
    name: "gener", 
    initialState: {
        gener: [], 
        isLoading: false
    },
    reducers: {
        // Action to set the loading flag to true when fetching starts
        getGenerFetch: (state) => { 
            state.isLoading = true;
        },
        // Action to update the gener array with the payload received from the API
        GenerSuccess: (state, action) => { 
            state.gener = action.payload;
            state.isLoading = false; 
        },
        // Action to handle failure cases, typically setting the loading flag to false
        GenerFailure: (state) => { 
            state.isLoading = false;
        },
    },
});

// Destructure and export the generated action creators for use in other parts of the application
export const { getGenerFetch, GenerSuccess, GenerFailure } = generSlice.actions;

// Export the reducer function generated by createSlice for use in the Redux store configuration
export default generSlice.reducer;